/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("OrderHeaderObjectPageObjectPage journey");

        opaTest("Navigate to OrderHeaderObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheOrderHeaderListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheOrderHeaderListGenerated.onTable().iCheckRows();
            When.onTheOrderHeaderListGenerated.onTable().iPressRow(0);

            Then.onTheOrderHeaderObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheOrderHeaderObjectPageGenerated.iCheckSection({ section: "HeaderData" });
            //When.onTheOrderHeaderObjectPageGenerated.iGoToSection({ section: "HeaderData", subSection: "FieldGroup1" });
            Then.onTheOrderHeaderObjectPageGenerated.iCheckSubSection({ section: "FieldGroup1" });
            Then.onTheOrderHeaderObjectPageGenerated.onForm({ section: "FieldGroup1" }).iCheckField({ property: "order_id" });
            Then.onTheOrderHeaderObjectPageGenerated.onForm({ section: "FieldGroup1" }).iCheckField({ property: "customer_id" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});