/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("OrderHeaderListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheOrderHeaderListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheOrderHeaderListGenerated.onFilterBar().iCheckFilterField({ property: "customer_id" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheOrderHeaderListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheOrderHeaderListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheOrderHeaderListGenerated.onTable(defaultTableId).iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            // When.onTheOrderHeaderListGenerated.onTable(defaultTableId).iPressAction("Ship Order");
            Then.onTheOrderHeaderListGenerated.onTable(defaultTableId).iCheckAction("Ship Order", { enabled: true });
            Then.onTheOrderHeaderListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"order_id":{"header":"order_id"},"customer_id":{"header":"customer_id"},"overall_status":{"header":"overall_status"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheOrderHeaderListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheOrderHeaderListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheOrderHeaderListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheOrderHeaderObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});